/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#ffd9e2",
        "error": "#ba1a1a",
        "surface-tint": "#732ee4",
        "on-surface": "#1d1a24",
        "primary-fixed-dim": "#d2bbff",
        "primary-container": "#7c3aed",
        "outline": "#7b7487",
        "surface-container-low": "#f9f1ff",
        "surface-container-lowest": "#ffffff",
        "on-error-container": "#93000a",
        "secondary-container": "#da2676",
        "on-secondary-fixed": "#3f001c",
        "tertiary-container": "#006d9c",
        "on-primary-container": "#ede0ff",
        "on-secondary-fixed-variant": "#8e0048",
        "on-tertiary-container": "#cfe9ff",
        "inverse-surface": "#332f3a",
        "primary": "#630ed4",
        "on-primary-fixed-variant": "#5a00c6",
        "tertiary-fixed-dim": "#89ceff",
        "on-secondary-container": "#fffbff",
        "background": "#fef7ff",
        "outline-variant": "#ccc3d8",
        "primary-fixed": "#eaddff",
        "on-primary": "#ffffff",
        "secondary-fixed-dim": "#ffb1c7",
        "surface-container-highest": "#e7e0ee",
        "on-secondary": "#ffffff",
        "error-container": "#ffdad6",
        "surface": "#fef7ff",
        "on-primary-fixed": "#25005a",
        "surface-dim": "#dfd7e6",
        "surface-container-high": "#ede5f4",
        "on-surface-variant": "#4a4455",
        "on-tertiary": "#ffffff",
        "surface-container": "#f3ebfa",
        "on-background": "#1d1a24",
        "tertiary": "#005479",
        "on-tertiary-fixed": "#001e2f",
        "secondary": "#b5005d",
        "inverse-on-surface": "#f6eefd",
        "on-tertiary-fixed-variant": "#004c6e",
        "tertiary-fixed": "#c9e6ff",
        "inverse-primary": "#d2bbff",
        "surface-bright": "#fef7ff",
        "on-error": "#ffffff",
        "surface-variant": "#e7e0ee"
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
      spacing: {
        "space-xl": "2rem",
        "space-xs": "0.25rem",
        "gutter-mobile": "0.75rem",
        "margin-tablet": "2rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "margin": "1.25rem",
        "space-sm": "0.5rem",
        "gutter": "1rem"
      },
      fontFamily: {
        "label-md": ["DM Sans"],
        "display-lg": ["Nunito Sans"],
        "headline-md": ["Nunito Sans"],
        "headline-sm": ["Nunito Sans"],
        "display-lg-mobile": ["Nunito Sans"],
        "label-lg": ["Nunito Sans"],
        "body-md": ["DM Sans"],
        "title-md": ["Nunito Sans"],
        "body-lg": ["DM Sans"],
        "label-sm": ["DM Sans"],
        "headline-lg": ["Nunito Sans"],
        "body-sm": ["DM Sans"]
      },
      fontSize: {
        "label-md": ["14px", { lineHeight: "18px", fontWeight: "500" }],
        "display-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "700" }],
        "display-lg-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "label-lg": ["16px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "700" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "title-md": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.04em", fontWeight: "700" }],
        "headline-lg": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }]
      }
    }
  },
  plugins: [],
}
